// Encargo semana 6 grupo 14

// creamos los DROP para que el codigo sea reutilizable
DROP TABLE REC_MED CASCADE CONSTRAINTS;
DROP TABLE DET_TIP CASCADE CONSTRAINTS;
DROP TABLE DIAG_DUR CASCADE CONSTRAINTS;
DROP TABLE DIAG_OBSE CASCADE CONSTRAINTS;
DROP TABLE DIGI_REC CASCADE CONSTRAINTS;
DROP TABLE MET_BAN CASCADE CONSTRAINTS;
DROP TABLE PAG_MET CASCADE CONSTRAINTS;
DROP TABLE TIPO_MED CASCADE CONSTRAINTS;
DROP TABLE TIPO_REC CASCADE CONSTRAINTS;
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS;
DROP TABLE DETALLE_RECETA CASCADE CONSTRAINTS;
DROP TABLE RECETA CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE DIGITADOR CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP TABLE PERSONA CASCADE CONSTRAINTS;
DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS;
DROP TABLE OBSERVACIONES CASCADE CONSTRAINTS;
DROP TABLE DURACION CASCADE CONSTRAINTS;
DROP TABLE TIPO_RECETA CASCADE CONSTRAINTS;
DROP TABLE METODO_PAGO CASCADE CONSTRAINTS;
DROP TABLE BANCO CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;


CREATE TABLE BANCO 
    ( 
     id_banco NUMBER  NOT NULL , 
     nombre   VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE BANCO 
    ADD CONSTRAINT BANCO_PK PRIMARY KEY ( id_banco ) ;

CREATE TABLE CIUDAD 
    ( 
     id_ciudad NUMBER  NOT NULL , 
     nombre    VARCHAR2 (50)  NOT NULL , 
     id_comuna NUMBER  NOT NULL 
    ) 
;

ALTER TABLE CIUDAD 
    ADD CONSTRAINT CIUDAD_PK PRIMARY KEY ( id_ciudad ) ;

CREATE TABLE COMUNA 
    ( 
     id_comuna NUMBER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1101 INCREMENT BY 1) , 
     nombre    VARCHAR2 (50)  NOT NULL , 
     id_region NUMBER  NOT NULL 
    ) 
;

ALTER TABLE COMUNA 
    ADD CONSTRAINT COMUNA_PK PRIMARY KEY ( id_comuna ) ;

CREATE TABLE DET_TIP 
    ( 
     id_detalle NUMBER  NOT NULL , 
     id_tipo    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE DET_TIP 
    ADD CONSTRAINT DETALLE_TIPO_PK PRIMARY KEY ( id_detalle, id_tipo ) ;

CREATE TABLE DETALLE_RECETA 
    ( 
     id_receta     NUMBER  NOT NULL , 
     id_detalle    NUMBER  NOT NULL , 
     fecha_emision DATE  NOT NULL 
    ) 
;

ALTER TABLE DETALLE_RECETA 
    ADD CONSTRAINT DETALLE_RECETA_PK PRIMARY KEY ( id_detalle ) ;

CREATE TABLE DIAG_DUR 
    ( 
     id_diagnostico NUMBER  NOT NULL , 
     id_duracion    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE DIAG_DUR 
    ADD CONSTRAINT DIAGNO_DURACION_PK PRIMARY KEY ( id_diagnostico, id_duracion ) ;

CREATE TABLE DIAG_OBSE 
    ( 
     id_diagnostico   NUMBER  NOT NULL , 
     id_observaciones NUMBER  NOT NULL 
    ) 
;

ALTER TABLE DIAG_OBSE 
    ADD CONSTRAINT DIAGNO_OBSERVA_PK PRIMARY KEY ( id_diagnostico, id_observaciones ) ;

CREATE TABLE DIAGNOSTICO 
    ( 
     id_detalle     NUMBER  NOT NULL , 
     id_diagnostico NUMBER  NOT NULL 
    ) 
;

ALTER TABLE DIAGNOSTICO 
    ADD CONSTRAINT DIAGNOSTICO_PK PRIMARY KEY ( id_diagnostico ) ;

CREATE TABLE DIGI_REC 
    ( 
     id_digitador NUMBER  NOT NULL , 
     id_receta    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE DIGI_REC 
    ADD CONSTRAINT DIGITADOR_RECETA_PK PRIMARY KEY ( id_digitador, id_receta ) ;

CREATE TABLE DIGITADOR 
    ( 
     id_digitador NUMBER  NOT NULL , 
     id_persona   NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX DIGITADOR__IDX ON DIGITADOR 
    ( 
     id_persona ASC 
    ) 
;

ALTER TABLE DIGITADOR 
    ADD CONSTRAINT DIGITADOR_PK PRIMARY KEY ( id_digitador ) ;

CREATE TABLE DURACION 
    ( 
     id_duracion NUMBER  NOT NULL , 
     inicio      DATE , 
     termino     DATE 
    ) 
;

ALTER TABLE DURACION 
    ADD CONSTRAINT DURACION_PK PRIMARY KEY ( id_duracion ) ;

CREATE TABLE ESPECIALIDAD 
    ( 
     id_especialidad NUMBER  GENERATED BY DEFAULT AS IDENTITY , 
     nombre          VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE ESPECIALIDAD 
    ADD CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY ( id_especialidad ) ;

CREATE TABLE MEDICAMENTO 
    ( 
     id_medicamento NUMBER  NOT NULL , 
     nombre         VARCHAR2 (50)  NOT NULL , 
     dosis          VARCHAR2 (100)  NOT NULL , 
     stock          NUMBER  NOT NULL , 
     id_detalle     NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX MEDICAMENTO__IDX ON MEDICAMENTO 
    ( 
     id_detalle ASC 
    ) 
;

ALTER TABLE MEDICAMENTO 
    ADD CONSTRAINT MEDICAMENTO_PK PRIMARY KEY ( id_medicamento ) ;

CREATE TABLE MEDICO 
    ( 
     id_persona      NUMBER  NOT NULL , 
     id_medico       NUMBER  NOT NULL , 
     telefono        NUMBER  NOT NULL , 
     id_especialidad NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX MEDICO__IDX ON MEDICO 
    ( 
     id_persona ASC 
    ) 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT MEDICO_PK PRIMARY KEY ( id_medico ) ;

CREATE TABLE MET_BAN 
    ( 
     id_metodo NUMBER  NOT NULL , 
     id_banco  NUMBER  NOT NULL 
    ) 
;

ALTER TABLE MET_BAN 
    ADD CONSTRAINT METODO_BANCO_PK PRIMARY KEY ( id_metodo, id_banco ) ;

CREATE TABLE METODO_PAGO 
    ( 
     id_metodo NUMBER  NOT NULL , 
     tipo      VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE METODO_PAGO 
    ADD CONSTRAINT METODO_PAGO_PK PRIMARY KEY ( id_metodo ) ;

CREATE TABLE OBSERVACIONES 
    ( 
     id_observaciones NUMBER  NOT NULL , 
     observaciones    VARCHAR2 (500)  NOT NULL 
    ) 
;

ALTER TABLE OBSERVACIONES 
    ADD CONSTRAINT OBSERVACIONES_PK PRIMARY KEY ( id_observaciones ) ;

CREATE TABLE PACIENTE 
    ( 
     id_paciente NUMBER  NOT NULL , 
     edad        NUMBER  NOT NULL , 
     id_persona  NUMBER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX PACIENTE__IDX ON PACIENTE 
    ( 
     id_persona ASC 
    ) 
;

ALTER TABLE PACIENTE 
    ADD CONSTRAINT PACIENTE_PK PRIMARY KEY ( id_paciente ) ;

CREATE TABLE PAG_MET 
    ( 
     id_pago   NUMBER  NOT NULL , 
     id_metodo NUMBER  NOT NULL 
    ) 
;

ALTER TABLE PAG_MET 
    ADD CONSTRAINT PAGO_METODO_PK PRIMARY KEY ( id_pago, id_metodo ) ;

CREATE TABLE PAGO 
    ( 
     id_receta    NUMBER  NOT NULL , 
     id_pago      NUMBER  NOT NULL , 
     monto_pagado NUMBER  NOT NULL , 
     fecha_pago   DATE  NOT NULL 
    ) 
;

ALTER TABLE PAGO 
    ADD CONSTRAINT PAGO_PK PRIMARY KEY ( id_pago ) ;

CREATE TABLE PERSONA 
    ( 
     id_ciudad   NUMBER  NOT NULL , 
     id_persona  NUMBER  NOT NULL , 
     rut         NUMBER  NOT NULL , 
     dv          VARCHAR2 (1)  NOT NULL , 
     direccion   VARCHAR2 (100)  NOT NULL , 
     nombre      VARCHAR2 (50)  NOT NULL , 
     apellidoPat VARCHAR2 (50)  NOT NULL , 
     apellidoMat VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PERSONA.dv IS '// Digito verificador del rut' 
;

ALTER TABLE PERSONA 
    ADD CONSTRAINT PERSONA_PK PRIMARY KEY ( id_persona ) ;

CREATE TABLE REC_MED 
    ( 
     id_receta      NUMBER  NOT NULL , 
     id_medicamento NUMBER  NOT NULL 
    ) 
;

ALTER TABLE REC_MED 
    ADD CONSTRAINT "RECETA-MED_PK" PRIMARY KEY ( id_receta, id_medicamento ) ;

CREATE TABLE RECETA 
    ( 
     id_receta NUMBER  NOT NULL , 
     codigo    VARCHAR2 (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN RECETA.codigo IS '// segun la receta de ejemplo los codigos son de 7 digitos' 
;

ALTER TABLE RECETA 
    ADD CONSTRAINT RECETA_PK PRIMARY KEY ( id_receta ) ;

CREATE TABLE REGION 
    ( 
     id_region NUMBER  NOT NULL , 
     nombre    VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE REGION 
    ADD CONSTRAINT REGION_PK PRIMARY KEY ( id_region ) ;

CREATE TABLE TIPO_MED 
    ( 
     id_medicamento NUMBER  NOT NULL , 
     id_tipoMed     NUMBER  NOT NULL , 
     tipo           VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE TIPO_MED 
    ADD CONSTRAINT TIPO_MED_PK PRIMARY KEY ( id_tipoMed ) ;

CREATE TABLE TIPO_REC 
    ( 
     id_tipo   NUMBER  NOT NULL , 
     tipo      VARCHAR2 (50)  NOT NULL , 
     id_receta NUMBER  NOT NULL 
    ) 
;

ALTER TABLE TIPO_REC 
    ADD CONSTRAINT TIPO_REC_PK PRIMARY KEY ( id_tipo ) ;

CREATE TABLE TIPO_RECETA 
    ( 
     id_tipo NUMBER  NOT NULL , 
     tipo    VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE TIPO_RECETA 
    ADD CONSTRAINT TIPO_RECETA_PK PRIMARY KEY ( id_tipo ) ;

ALTER TABLE CIUDAD 
    ADD CONSTRAINT CIU_COM_FK FOREIGN KEY 
    ( 
     id_comuna
    ) 
    REFERENCES COMUNA 
    ( 
     id_comuna
    ) 
;

ALTER TABLE COMUNA 
    ADD CONSTRAINT COM_REG_FK FOREIGN KEY 
    ( 
     id_region
    ) 
    REFERENCES REGION 
    ( 
     id_region
    ) 
;

ALTER TABLE DETALLE_RECETA 
    ADD CONSTRAINT DET_REC_REC_FK FOREIGN KEY 
    ( 
     id_receta
    ) 
    REFERENCES RECETA 
    ( 
     id_receta
    ) 
;

ALTER TABLE DET_TIP 
    ADD CONSTRAINT DET_TIP_DET_REC_FK FOREIGN KEY 
    ( 
     id_detalle
    ) 
    REFERENCES DETALLE_RECETA 
    ( 
     id_detalle
    ) 
;

ALTER TABLE DET_TIP 
    ADD CONSTRAINT DET_TIP_TIP_REC_FK FOREIGN KEY 
    ( 
     id_tipo
    ) 
    REFERENCES TIPO_RECETA 
    ( 
     id_tipo
    ) 
;

ALTER TABLE DIAGNOSTICO 
    ADD CONSTRAINT DIAG_DET_REC_FK FOREIGN KEY 
    ( 
     id_detalle
    ) 
    REFERENCES DETALLE_RECETA 
    ( 
     id_detalle
    ) 
;

ALTER TABLE DIAG_DUR 
    ADD CONSTRAINT DIAG_DUR_DIAG_FK FOREIGN KEY 
    ( 
     id_diagnostico
    ) 
    REFERENCES DIAGNOSTICO 
    ( 
     id_diagnostico
    ) 
;

ALTER TABLE DIAG_DUR 
    ADD CONSTRAINT DIAG_DURA_DUR_FK FOREIGN KEY 
    ( 
     id_duracion
    ) 
    REFERENCES DURACION 
    ( 
     id_duracion
    ) 
;

ALTER TABLE DIAG_OBSE 
    ADD CONSTRAINT DIAG_OBSER_DIAG_FK FOREIGN KEY 
    ( 
     id_diagnostico
    ) 
    REFERENCES DIAGNOSTICO 
    ( 
     id_diagnostico
    ) 
;

ALTER TABLE DIAG_OBSE 
    ADD CONSTRAINT DIAG_OBSER_OBSER_FK FOREIGN KEY 
    ( 
     id_observaciones
    ) 
    REFERENCES OBSERVACIONES 
    ( 
     id_observaciones
    ) 
;

ALTER TABLE DIGITADOR 
    ADD CONSTRAINT DIGI_PER_FK FOREIGN KEY 
    ( 
     id_persona
    ) 
    REFERENCES PERSONA 
    ( 
     id_persona
    ) 
;

ALTER TABLE DIGI_REC 
    ADD CONSTRAINT DIGI_REC_DIGI_FK FOREIGN KEY 
    ( 
     id_digitador
    ) 
    REFERENCES DIGITADOR 
    ( 
     id_digitador
    ) 
;

ALTER TABLE DIGI_REC 
    ADD CONSTRAINT DIGI_REC_REC_FK FOREIGN KEY 
    ( 
     id_receta
    ) 
    REFERENCES RECETA 
    ( 
     id_receta
    ) 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT MED_ESPE_FK FOREIGN KEY 
    ( 
     id_especialidad
    ) 
    REFERENCES ESPECIALIDAD 
    ( 
     id_especialidad
    ) 
;

ALTER TABLE MEDICO 
    ADD CONSTRAINT MED_PER_FK FOREIGN KEY 
    ( 
     id_persona
    ) 
    REFERENCES PERSONA 
    ( 
     id_persona
    ) 
;

ALTER TABLE MEDICAMENTO 
    ADD CONSTRAINT MEDI_DET_REC_FK FOREIGN KEY 
    ( 
     id_detalle
    ) 
    REFERENCES DETALLE_RECETA 
    ( 
     id_detalle
    ) 
;

ALTER TABLE MET_BAN 
    ADD CONSTRAINT MET_BAN_BAN_FK FOREIGN KEY 
    ( 
     id_banco
    ) 
    REFERENCES BANCO 
    ( 
     id_banco
    ) 
;

ALTER TABLE MET_BAN 
    ADD CONSTRAINT MET_BAN_MET_PAGO_FK FOREIGN KEY 
    ( 
     id_metodo
    ) 
    REFERENCES METODO_PAGO 
    ( 
     id_metodo
    ) 
;

ALTER TABLE PACIENTE 
    ADD CONSTRAINT PAC_PER_FK FOREIGN KEY 
    ( 
     id_persona
    ) 
    REFERENCES PERSONA 
    ( 
     id_persona
    ) 
;

ALTER TABLE PAG_MET 
    ADD CONSTRAINT PAG_MET_MET_PAG_FK FOREIGN KEY 
    ( 
     id_metodo
    ) 
    REFERENCES METODO_PAGO 
    ( 
     id_metodo
    ) 
;

ALTER TABLE PAG_MET 
    ADD CONSTRAINT PAG_MET_PAG_FK FOREIGN KEY 
    ( 
     id_pago
    ) 
    REFERENCES PAGO 
    ( 
     id_pago
    ) 
;

ALTER TABLE PAGO 
    ADD CONSTRAINT PAG_REC_FK FOREIGN KEY 
    ( 
     id_receta
    ) 
    REFERENCES RECETA 
    ( 
     id_receta
    ) 
;

ALTER TABLE PERSONA 
    ADD CONSTRAINT PER_CIU_FK FOREIGN KEY 
    ( 
     id_ciudad
    ) 
    REFERENCES CIUDAD 
    ( 
     id_ciudad
    ) 
;

ALTER TABLE REC_MED 
    ADD CONSTRAINT "REC-MED_MEDICA_FK" FOREIGN KEY 
    ( 
     id_medicamento
    ) 
    REFERENCES MEDICAMENTO 
    ( 
     id_medicamento
    ) 
;

ALTER TABLE REC_MED 
    ADD CONSTRAINT "REC-MED_REC_FK" FOREIGN KEY 
    ( 
     id_receta
    ) 
    REFERENCES RECETA 
    ( 
     id_receta
    ) 
;

ALTER TABLE TIPO_MED 
    ADD CONSTRAINT TIP_MED_MEDI_FK FOREIGN KEY 
    ( 
     id_medicamento
    ) 
    REFERENCES MEDICAMENTO 
    ( 
     id_medicamento
    ) 
;

ALTER TABLE TIPO_REC 
    ADD CONSTRAINT TIPO_REC_REC_FK FOREIGN KEY 
    ( 
     id_receta
    ) 
    REFERENCES RECETA 
    ( 
     id_receta
    ) 
;

// anadimos las restricciones y reglas de negocio

// hacemos que el telefono sea unico para cada medico
ALTER TABLE MEDICO ADD CONSTRAINT uk_telefono_med UNIQUE (telefono);
// agregamos el check de los digitos del rut
ALTER TABLE PERSONA ADD CONSTRAINT chk_dv CHECK (dv IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K'));
// agregamos los medios de pago
ALTER TABLE METODO_PAGO ADD CONSTRAINT chk_tipo_pago (tipo IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA'));
// agregamos columna para el precio del medicamento
ALTER TABLE MEDICAMENTO ADD precio NUMBER;
// creamos la restriccion de precio 
ALTER TABLE MEDICAMENTO ADD CONSTRAINT chk_rango_precios CHECK (precio BETWEEN 1000 AND 2000000);
// eliminamos la columan EDAD y agregamos fecha nacimiento
ALTER TABLE PACIENTE DROP COLUMN edad;
// anadimos la fecha de nacimiento
ALTER TABLE PACIENTE ADD nacimiento DATE;


